name: tradecraftHub
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19=hecd8cb5_0
  - certifi=2020.12.5=py39hecd8cb5_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1i=h9ed2024_0
  - pip=20.3.3=py39hecd8cb5_0
  - python=3.9.1=h88f2d9e_2
  - readline=8.1=h9ed2024_0
  - setuptools=52.0.0=py39hecd8cb5_0
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - tzdata=2020f=h52ac0ba_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - anyio==2.1.0
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - babel==2.9.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cffi==1.14.4
    - chardet==4.0.0
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.10
    - ipykernel==5.4.3
    - ipython==7.20.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.0
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.11
    - jupyter-core==4.7.1
    - jupyter-server==1.3.0
    - jupyterlab==3.0.7
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.2.0
    - kiwisolver==1.3.1
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - nbclassic==0.2.6
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - notebook==6.2.0
    - numpy==1.20.1
    - packaging==20.9
    - pandas==1.2.1
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.14
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.7.4
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyzmq==22.0.2
    - requests==2.25.1
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - seaborn==0.11.1
    - send2trash==1.5.0
    - six==1.15.0
    - sniffio==1.2.0
    - terminado==0.9.2
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tornado==6.1
    - traitlets==5.0.5
    - urllib3==1.26.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
prefix: /Users/guillermo/opt/anaconda3/envs/tradecraftHub
